//Code of trash collector system
#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void clamp()
{
	nSyncedMotors=synchAC;
	nSyncedTurnRatio=100;

	nMotorEncoder[B]=0;
	nMotorEncoderTarget[B]=100;
	motor[B]=-25;
	wait1Msec(2000);

	nMotorEncoder[A]=0;
	nMotorEncoderTarget[A]=155;
	motor[A]=25;

	wait1Msec(2000);
	nMotorEncoder[B]=0;
	nMotorEncoderTarget[B]=50;
	motor[B]=25;
	wait1Msec(1000);

	nMotorEncoder[A]=0;
	nMotorEncoderTarget[A]=160;
	motor[A]=-15;
	wait1Msec(2000);

	nMotorEncoder[B]=0;
	nMotorEncoderTarget[B]=50;
	motor[B]=25;
	wait1Msec(1000);
}
task main()
{
	int i;
	for(i=0;i<10;i++)
	{
    while(SensorValue(sonar)>20)
		{
			motor[rightMotor]=5;
			motor[leftMotor]=5;
		}
		motor[rightMotor]=0;
		motor[leftMotor]=0;
		clamp();
	}
}
